/******** DO NOT EDIT THIS FILE ********/
#include <stdio.h>
#include "test_jobqueue_common.h"
#include "test_ipc_jobqueue.h"
#include "../ipc_jobqueue.h"
#include "procs4tests.h"

int main(int argc, char** argv) {
    return munit_suite_main(&suite, NULL, argc, argv);
}

void* test_setup(const MunitParameter params[], void* user_data) {
    test_jq_t* test_jq = (test_jq_t*) malloc(sizeof(test_jq_t));

    ipc_jobqueue_t* q = ipc_jobqueue_new(new_init_proc());
    
    test_jq->q = q;
    jobqueue_t* jq = (jobqueue_t*) q->addr;
    
    // assert valid queue
    assert_queue_initialised(jq);

    test_jq->head = &jq->head;
    test_jq->tail = &jq->tail;
    test_jq->buf_size = &jq->buf_size;
    test_jq->jobs = jq->jobs;
    test_jq->capacity = (size_t (*)(void*)) ipc_jobqueue_capacity;
    test_jq->is_full = (bool (*)(void*)) ipc_jobqueue_is_full;
    test_jq->is_empty = (bool (*)(void*)) ipc_jobqueue_is_empty;
    test_jq->enqueue = (void (*)(void*, job_t*))  ipc_jobqueue_enqueue;
    test_jq->dequeue = (job_t* (*)(void*, job_t*)) ipc_jobqueue_dequeue;
    test_jq->peekhead = (job_t* (*)(void*, job_t*)) ipc_jobqueue_peekhead;
    test_jq->peektail = (job_t* (*)(void*, job_t*)) ipc_jobqueue_peektail;
        
    return test_jq;
}

void test_tear_down(void* fixture) {
    test_jq_t* test_jq = (test_jq_t*) fixture;
    ipc_jobqueue_t* q = (ipc_jobqueue_t*) test_jq->q;
   
    proc_t* p = q->proc;
    ipc_delete(q);
    proc_delete(p);
    free(test_jq);
}

MunitResult test_ipc_jobqueue_capacity(const MunitParameter params[], 
    void* fixture) {
    return test_jq_capacity((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_capacity_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_capacity_null((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_dequeue_fullq(const MunitParameter params[], 
    void* fixture) {
    return test_jq_dequeue_fullq((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_dequeue_inout(const MunitParameter params[], 
    void* fixture) {
    return test_jq_dequeue_inout((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_dequeue_emptyq(const MunitParameter params[], 
    void* fixture) {
    return test_jq_dequeue_emptyq((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_dequeue_heap(const MunitParameter params[], 
    void* fixture) {
    return test_jq_dequeue_heap((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_dequeue_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_dequeue_null((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_enqueue_tofull(const MunitParameter params[], 
    void* fixture) {
    return test_jq_enqueue_tofull((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_enqueue_inout(const MunitParameter params[], 
    void* fixture) {
    return test_jq_enqueue_inout((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_enqueue_fullq(const MunitParameter params[], 
    void* fixture) {
    return test_jq_enqueue_fullq((test_jq_t*) fixture);
}
 
MunitResult test_ipc_jobqueue_enqueue_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_enqueue_null((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_is_empty(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_empty((test_jq_t*) fixture);
}
 
MunitResult test_ipc_jobqueue_is_empty_notempty(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_empty_notempty((test_jq_t*) fixture);
}
 
MunitResult test_ipc_jobqueue_is_empty_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_empty_null((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_is_full_empty(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_full_empty((test_jq_t*) fixture);
}
 
MunitResult test_ipc_jobqueue_is_full_filling(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_full_filling((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_is_full_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_full_null((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_peekhead_empty(const MunitParameter params[], 
    void* fixture) {
    return test_jq_peekhead_empty((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_peekhead_full(const MunitParameter params[], 
    void* fixture) {
    return test_jq_peekhead_full((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_peekhead_heap(const MunitParameter params[], 
    void* fixture) {
    return test_jq_peekhead_heap((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_peekhead_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_peekhead_null((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_peektail_empty(const MunitParameter params[], 
    void* fixture) {
    return test_jq_peektail_empty((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_peektail_full(const MunitParameter params[], 
    void* fixture) {
    return test_jq_peektail_full((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_peektail_heap(const MunitParameter params[], 
    void* fixture) {
    return test_jq_peektail_heap((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_peektail_wrap(const MunitParameter params[], 
    void* fixture) {
    return test_jq_peektail_wrap((test_jq_t*) fixture);
}

MunitResult test_ipc_jobqueue_peektail_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_peektail_null((test_jq_t*) fixture);
}
