/******** DO NOT EDIT THIS FILE ********/
#include <stdio.h>
#include "test_jobqueue_common.h"
#include "test_jobqueue.h"

int main(int argc, char** argv) {
    return munit_suite_main(&suite, NULL, argc, argv);
}

static void assert_queue_initialised(jobqueue_t* q) {
    assert_not_null(q);
    assert_int(q->head, ==, 0);
    assert_int(q->tail, ==, 0);
    assert_int(q->buf_size, ==, QUEUE_SIZE);
    
    assert_true(jobs_initialised(q->jobs, q->buf_size));    
}

void* test_setup(const MunitParameter params[], void* user_data) {
    test_jq_t* test_jq = (test_jq_t*) malloc(sizeof(test_jq_t));
    
    jobqueue_t* q = (jobqueue_t*) malloc(sizeof(jobqueue_t));
    
    jobqueue_init(q);
    
    // assert valid queue (tests jobqueue_init as side effect)
    assert_queue_initialised(q);
    
    test_jq->q = q;
    
    test_jq->head = &q->head;
    test_jq->tail = &q->tail;
    test_jq->buf_size = &q->buf_size;
    test_jq->jobs = q->jobs;
    test_jq->capacity = (size_t (*)(void*)) jobqueue_capacity;
    test_jq->is_full = (bool (*)(void*)) jobqueue_is_full;
    test_jq->is_empty = (bool (*)(void*))jobqueue_is_empty;
    test_jq->enqueue = (void (*)(void*, job_t*)) jobqueue_enqueue;
    test_jq->dequeue = (job_t* (*)(void*, job_t*)) jobqueue_dequeue;
    test_jq->peekhead = (job_t* (*)(void*, job_t*)) jobqueue_peekhead;
    test_jq->peektail = (job_t* (*)(void*, job_t*)) jobqueue_peektail;
    
    return test_jq;
}

void test_tear_down(void* fixture) {
    test_jq_t* test_jq = (test_jq_t*) fixture;
    free(test_jq->q);
    
    free(test_jq);
}

MunitResult test_jobqueue_new(const MunitParameter params[], 
    void* fixture) {
    jobqueue_t* q = jobqueue_new();
    
    assert_not_null(q);
    assert_queue_initialised(q);
    
    free(q);
    
    return MUNIT_OK;
}

MunitResult test_jobqueue_delete(const MunitParameter params[], 
    void* fixture) {
    test_jq_t* test_jq = (test_jq_t*) fixture;

    /* the following should just not cause errors */
    jobqueue_delete((jobqueue_t*) test_jq->q);
    
    /* check NULL OK */    
    jobqueue_delete(NULL);
    
    /* complete what tear_down would do */
    free(test_jq);

    return MUNIT_OK;
}

MunitResult test_jobqueue_capacity(const MunitParameter params[], 
    void* fixture) {
    return test_jq_capacity((test_jq_t*) fixture);
}

MunitResult test_jobqueue_capacity_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_capacity_null((test_jq_t*) fixture);
}

MunitResult test_jobqueue_dequeue_fullq(const MunitParameter params[], 
    void* fixture) {
    return test_jq_dequeue_fullq((test_jq_t*) fixture);
}

MunitResult test_jobqueue_dequeue_inout(const MunitParameter params[], 
    void* fixture) {
    return test_jq_dequeue_inout((test_jq_t*) fixture);
}

MunitResult test_jobqueue_dequeue_emptyq(const MunitParameter params[], 
    void* fixture) {
    return test_jq_dequeue_emptyq((test_jq_t*) fixture);
}

MunitResult test_jobqueue_dequeue_heap(const MunitParameter params[], 
    void* fixture) {
    return test_jq_dequeue_heap((test_jq_t*) fixture);
}

MunitResult test_jobqueue_dequeue_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_dequeue_null((test_jq_t*) fixture);
}

MunitResult test_jobqueue_enqueue_tofull(const MunitParameter params[], 
    void* fixture) {
    return test_jq_enqueue_tofull((test_jq_t*) fixture);
}

MunitResult test_jobqueue_enqueue_inout(const MunitParameter params[], 
    void* fixture) {
    return test_jq_enqueue_inout((test_jq_t*) fixture);
}

MunitResult test_jobqueue_enqueue_fullq(const MunitParameter params[], 
    void* fixture) {
    return test_jq_enqueue_fullq((test_jq_t*) fixture);
}
 
MunitResult test_jobqueue_enqueue_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_enqueue_null((test_jq_t*) fixture);
}

MunitResult test_jobqueue_is_empty(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_empty((test_jq_t*) fixture);
}
 
MunitResult test_jobqueue_is_empty_notempty(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_empty_notempty((test_jq_t*) fixture);
}
 
MunitResult test_jobqueue_is_empty_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_empty_null((test_jq_t*) fixture);
}

MunitResult test_jobqueue_is_full_empty(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_full_empty((test_jq_t*) fixture);
}
 
MunitResult test_jobqueue_is_full_filling(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_full_filling((test_jq_t*) fixture);
}

MunitResult test_jobqueue_is_full_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_full_null((test_jq_t*) fixture);
}

MunitResult test_jobqueue_peekhead_empty(const MunitParameter params[], 
    void* fixture) {
    return test_jq_peekhead_empty((test_jq_t*) fixture);
}

MunitResult test_jobqueue_peekhead_full(const MunitParameter params[], 
    void* fixture) {
    return test_jq_peekhead_full((test_jq_t*) fixture);
}

MunitResult test_jobqueue_peekhead_heap(const MunitParameter params[], 
    void* fixture) {
    return test_jq_peekhead_heap((test_jq_t*) fixture);
}

MunitResult test_jobqueue_peekhead_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_peekhead_null((test_jq_t*) fixture);
}

MunitResult test_jobqueue_peektail_empty(const MunitParameter params[], 
    void* fixture) {
    return test_jq_peektail_empty((test_jq_t*) fixture);
}

MunitResult test_jobqueue_peektail_full(const MunitParameter params[], 
    void* fixture) {
    return test_jq_peektail_full((test_jq_t*) fixture);
}

MunitResult test_jobqueue_peektail_heap(const MunitParameter params[], 
    void* fixture) {
    return test_jq_peektail_heap((test_jq_t*) fixture);
}

MunitResult test_jobqueue_peektail_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_peektail_null((test_jq_t*) fixture);
}
