#******** DO NOT EDIT THIS FILE ********#
# this is the main make build file project

include make.cfg

# top-level targets
all: tests
.PHONY: all

tests: $(depend_sources_r01:%=$(testbin)/test_%)
.PHONY: tests

depend:
	@make -f $(make_depend)

clean: clean_$(bin) clean_core clean_$(objects) clean_out 
.PHONY: clean

clean_all: clean clean_depend clean_dist clean_munit_lib
.PHONY: clean_all

-include $(depend_sources_r01:%=./$(depend)/%.d)
-include $(testdepend_sources_r01:%=./$(testdepend)/%.d)

# test targets
$(testbin)/test_joblog: $(testobjects)/test_joblog.o \
    $(job_lib) $(joblog_lib) $(munit_lib) $(procs4tests_lib) $(proc_lib) \
    | $(testbin)
	$(CC) $(CFLAGS) $^ -o $@

$(testbin)/test_jobqueue: $(testobjects)/test_jobqueue.o $(job_lib) \
    $(objects)/jobqueue.o $(munit_lib) $(test_jobqueue_common_lib) | $(testbin)
	$(CC) $(CFLAGS) $^ -o $@

$(testbin)/test_%: $(testobjects)/test_%.o $(objects)/%.o $(munit_lib) \
    | $(testbin)
	$(CC) $(CFLAGS) $^ -o $@

# all object targets
all_objects: $(sources:%=$(objects)/%.o)
.PHONY: all_objects

all_testobjects: $(tests:%=$(testobjects)/%.o)
.PHONY: all_testobjects

# clean sub-targets
clean_$(bin):
	-rm -f ./a.out
	-rm -rf ./$(testbin)
	-rm -rf ./$(bin)
.PHONY: clean_$(bin)
	
clean_core:
	-rm -f ./core.*
	-rm -f ./$(bin)/core.*
	-rm -f ./$(testbin)/core.*
.PHONY: clean_core
    
clean_$(objects):
	-rm -f ./*.o
	-rm -rf ./$(objects)
	-rm -rf ./$(testobjects)
.PHONY: clean_obj

clean_munit_lib:
	-rm -f $(munit_lib)
.PHONY: clean_munit

clean_out:
	-rm -rf ./out
.PHONY: clean_out

clean_$(dist):
	-rm -rf ./$(dist)
.PHONY: clean_$(dist)

clean_$(depend):
	@make -f $(make_depend) clean
.PHONY: clean_$(depend)

# make directory sub-targets
$(bin): ; -@mkdir -p ./$@

$(testbin): ; -@mkdir -p ./$@

$(testobjects): ; -@mkdir -p ./$@

$(objects): ; -@mkdir -p ./$@

