/******** DO NOT EDIT THIS FILE ********/
#ifndef _SIM_CONFIG_H
#define _SIM_CONFIG_H


#define QUEUE_SIZE 128   /* size of the buffer used by a job queue */
                        
#define MAX_NAME_SIZE 32 /* maximum bytes for a name - used for shared object
                          * names and job labels
                          */

extern const char* SHOBJ_NAME_FORMAT;

#define PAD_CHAR '*'

#define MIN_WORK_DEFAULT 20
#define MAX_WORK_DEFAULT 40
#define PROC_SKIP_FACTOR 2

/* 
 * JOB_LOG_ENTRY_SIZE - the size of an entry in a job log - the number of 
 * the number of characters for each line of a job log
 */
#define JOBLOG_ENTRY_SIZE 59
/* JOB_LOG_PATH - the parent directory for logs */
extern const char* JOBLOG_PATH;         // the parent directory for logs
/* JOBLOG_NAME_FMT - string format for the name of a log file */
extern const char* JOBLOG_NAME_FMT;
/* JOBLOG_ENTRY_FMT - string format for a job log entry */
extern const char* JOBLOG_ENTRY_FMT; 

#endif